defaults:
  - base_config
  - _self_

sampler:
  n_particles:  34
  n_spin_up:    17
  n_protons:    14
  n_void_steps: 500
  n_walkers:    50
  kick_size:    0.1
  walk_precision: float32

wavefunction:
  mean_subtract: True
  mirror:        True
  time_reversal: False
  backflow:      True
  activation:    celu
  confinement:   0.05

iterations: 1500
