defaults:
  - base_config
  - _self_


sampler:
  n_particles:  3
  n_spin_up:    2
  n_protons:    1
  n_void_steps: 500
  n_walkers:    750
  kick_size:    0.5
  walk_precision: float32

wavefunction:
  mean_subtract: True
  activation: celu
  confinement: 0.5
  gnn:
    symmetric: False
iterations: 1500
